import {
  Capture, Session, Finding, Host, ScoreData, Policy
} from '../types';

export const DEFAULT_POLICY: Policy = {
  tls_min_version: 'TLS 1.2',
  cert_max_validity_days: 398,
  rsa_min_key_bits: 2048,
  ec_min_key_bits: 224,
  allow_self_signed: false,
  require_forward_secrecy: true,
  require_starttls: true,
  repeated_failures_threshold: 3,
  scoring_weights: {
    protocol_security: 25,
    cryptographic_security: 30,
    certificate_security: 25,
    behavioral_security: 20,
  },
};

export const DEMO_CAPTURE: Capture = {
  capture_id: 'cap-demo-160',
  filename: 'securemailscope_demo_corpus.pcap',
  size_bytes: 145892,
  status: 'COMPLETE',
  completeness: 100,
  uploaded_at: new Date(Date.now() - 3600000).toISOString(),
  processed_at: new Date().toISOString(),
  processing_stage: 'COMPLETE',
  passive_visibility_rate: 98.4,
};

export const DEMO_SCORE: ScoreData = {
  score_id: 'score-demo-160',
  scope: 'CAPTURE',
  scope_id: 'cap-demo-160',
  posture_score: 65,
  breakdown: [
    { category: 'Protocol Security', deduction: 15, findings_count: 32, grouped_rules: ['RULE-01', 'RULE-02'] },
    { category: 'Cryptographic Security', deduction: 10, findings_count: 48, grouped_rules: ['RULE-05', 'RULE-06', 'RULE-09'] },
    { category: 'Certificate Security', deduction: 6, findings_count: 35, grouped_rules: ['RULE-11', 'RULE-13'] },
    { category: 'Behavioral & Anomaly', deduction: 4, findings_count: 45, grouped_rules: ['ML-ANOMALY-01', 'RULE-18'] },
  ],
  audit_trail: [
    {
      session_id: 'sess-001',
      category: 'Protocol Security',
      primary_rule: 'RULE-01',
      primary_severity: 'HIGH',
      findings_count: 2,
      deduction: 15,
      all_rules: ['RULE-01', 'RULE-09']
    },
    {
      session_id: 'sess-004',
      category: 'Cryptographic Security',
      primary_rule: 'RULE-05',
      primary_severity: 'HIGH',
      findings_count: 1,
      deduction: 10,
      all_rules: ['RULE-05']
    },
    {
      session_id: 'sess-007',
      category: 'STARTTLS Upgrade',
      primary_rule: 'RULE-18',
      primary_severity: 'CRITICAL',
      findings_count: 2,
      deduction: 20,
      all_rules: ['RULE-18', 'RULE-19']
    }
  ],
  disclaimer: 'Score calibrated using 21 RFC/NIST deterministic compliance checks with anti-double-counting logic and unsupervised Isolation Forest outlier detection.',
};

export const DEMO_HOSTS: Host[] = [
  { host_id: 'host-1', capture_id: 'cap-demo-160', ip: '10.0.0.25', hostname: 'mail.enterprise-relay.org', session_count: 85, posture_score: 82 },
  { host_id: 'host-2', capture_id: 'cap-demo-160', ip: '192.168.1.11', hostname: 'internal-smtp.lan', session_count: 35, posture_score: 45 },
  { host_id: 'host-3', capture_id: 'cap-demo-160', ip: '192.168.1.50', hostname: 'imap-secure.cluster.local', session_count: 25, posture_score: 90 },
  { host_id: 'host-4', capture_id: 'cap-demo-160', ip: '192.168.1.99', hostname: 'legacy-pop3.dept.local', session_count: 15, posture_score: 30 },
];

export const DEMO_FINDINGS: Finding[] = [
  {
    finding_id: 'find-001',
    capture_id: 'cap-demo-160',
    session_id: 'sess-001',
    rule_id: 'RULE-01',
    title: 'Obsolete TLS 1.0 Negotiated on Mail Relay',
    severity: 'HIGH',
    confidence: 'DIRECT',
    protocol: 'SMTP',
    evidence_json: { frame_index: 14, byte_offset: 54, hex: '0301', negotiated_version: 'TLS 1.0' },
    impact: 'Exposes session to downgrade attacks and BEAST cryptographic vulnerability.',
    recommendation: 'Enforce minimum TLS 1.2 or modern TLS 1.3 across mail server cipher configurations.',
    limitations_json: { observable_on_wire: true },
    standards_ref: 'IETF RFC 8996 (Deprecating TLS 1.0 & 1.1)',
    category: 'Protocol Security',
  },
  {
    finding_id: 'find-002',
    capture_id: 'cap-demo-160',
    session_id: 'sess-004',
    rule_id: 'RULE-05',
    title: 'Weak 3DES-CBC Cipher Suite Selected',
    severity: 'HIGH',
    confidence: 'DIRECT',
    protocol: 'IMAP',
    evidence_json: { frame_index: 42, cipher_code: '0x000A', cipher_name: 'TLS_RSA_WITH_3DES_EDE_CBC_SHA' },
    impact: 'Vulnerable to Sweet32 collision attacks on 64-bit block ciphers.',
    recommendation: 'Disable 3DES cipher suites; mandate AES-GCM or ChaCha20-Poly1305.',
    limitations_json: { observable_on_wire: true },
    standards_ref: 'NIST SP 800-52 Rev. 2 / CVE-2016-2183',
    category: 'Cryptographic Security',
  },
  {
    finding_id: 'find-003',
    capture_id: 'cap-demo-160',
    session_id: 'sess-007',
    rule_id: 'RULE-18',
    title: 'STARTTLS Negotiation Stripped / Plaintext Fallback',
    severity: 'CRITICAL',
    confidence: 'DIRECT',
    protocol: 'SMTP',
    evidence_json: { frame_index: 88, server_banner: '250-STARTTLS stripped', auth_in_plaintext: true },
    impact: 'Plaintext authentication observed over unencrypted TCP stream. High risk of credential harvesting.',
    recommendation: 'Configure MTA with mandatory STARTTLS encryption (reject unencrypted AUTH).',
    limitations_json: { observable_on_wire: true },
    standards_ref: 'RFC 3207 / MITRE ATT&CK T1557',
    category: 'Protocol Security',
  },
  {
    finding_id: 'find-004',
    capture_id: 'cap-demo-160',
    session_id: 'sess-009',
    rule_id: 'RULE-09',
    title: 'Static RSA Key Exchange Without Perfect Forward Secrecy',
    severity: 'MEDIUM',
    confidence: 'DIRECT',
    protocol: 'SMTP',
    evidence_json: { frame_index: 104, cipher_code: '0x002F', key_exchange: 'RSA' },
    impact: 'Past recorded network traffic can be retroactively decrypted if private key is ever compromised.',
    recommendation: 'Migrate to ephemeral Diffie-Hellman key exchanges (ECDHE with X25519 or secp256r1).',
    limitations_json: { observable_on_wire: true },
    standards_ref: 'NIST SP 800-52 Rev. 2 §3.3.1',
    category: 'Cryptographic Security',
  },
  {
    finding_id: 'find-005',
    capture_id: 'cap-demo-160',
    session_id: 'sess-012',
    rule_id: 'RULE-11',
    title: 'Expired X.509 Server Certificate Presented',
    severity: 'HIGH',
    confidence: 'DIRECT',
    protocol: 'POP3',
    evidence_json: { frame_index: 122, not_after: '2025-12-31T23:59:59Z', subject: 'CN=legacy-pop3.dept.local' },
    impact: 'Mail clients cannot cryptographically verify server authenticity, exposing users to MITM.',
    recommendation: 'Renew and deploy unexpired X.509 certificate validated by trusted CA.',
    limitations_json: { observable_on_wire: true },
    standards_ref: 'RFC 5280 §4.1.2.5',
    category: 'Certificate Security',
  },
  {
    finding_id: 'find-006',
    capture_id: 'cap-demo-160',
    session_id: 'sess-015',
    rule_id: 'ML-ANOMALY-01',
    title: 'Anomalous Handshake Fingerprint (Isolation Forest)',
    severity: 'MEDIUM',
    confidence: 'HIGH CONFIDENCE',
    protocol: 'SMTP',
    evidence_json: { anomaly_score: -0.68, entropy_deviation: 3.42, ja3_hash: '7c86a60e0a54e9bc' },
    impact: 'Client handshake fingerprint deviates significantly from enterprise baseline. Potential automated scanner or custom evasion tool.',
    recommendation: 'Inspect client host IP 192.168.1.11 for unauthorized script or scanning utility.',
    limitations_json: { model: 'IsolationForest_v1.0' },
    standards_ref: 'TLSpectra Unsupervised Behavioral ML Baseline',
    category: 'Behavioral & Anomaly',
  },
];

export const DEMO_SESSIONS: Session[] = [
  {
    session_id: 'sess-001',
    capture_id: 'cap-demo-160',
    protocol: 'SMTP',
    protocol_confidence: 'DIRECT',
    client_ip: '192.168.1.11',
    client_port: 52140,
    server_ip: '10.0.0.25',
    server_port: 587,
    starttls_state: 'UPGRADED_TLS',
    capture_completeness: 100,
    packet_count: 28,
    byte_count: 8420,
    auth_observed: true,
    auth_plaintext: false,
    handshake: {
      handshake_id: 'hs-001',
      session_id: 'sess-001',
      version: 'TLS 1.0',
      cipher_suite: 'TLS_RSA_WITH_AES_128_CBC_SHA',
      key_exchange: 'RSA',
      forward_secrecy: false,
      sni: 'mail.enterprise-relay.org',
      supported_groups: [],
      session_resumption: false,
      handshake_sequence: ['ClientHello', 'ServerHello', 'Certificate', 'ServerHelloDone', 'ClientKeyExchange', 'ChangeCipherSpec', 'Finished'],
      alerts: [],
      duration_ms: 45.2,
      certificates: [
        {
          cert_id: 'cert-1',
          handshake_id: 'hs-001',
          subject: 'CN=mail.enterprise-relay.org',
          issuer: 'CN=Enterprise Intermediate CA',
          san: ['mail.enterprise-relay.org', 'relay.enterprise.org'],
          not_before: '2024-01-01',
          not_after: '2026-12-31',
          public_key_alg: 'RSA',
          key_bits: 2048,
          signature_alg: 'sha256WithRSAEncryption',
          chain_position: 0,
          is_self_signed: false,
        }
      ]
    }
  },
  {
    session_id: 'sess-002',
    capture_id: 'cap-demo-160',
    protocol: 'SMTP',
    protocol_confidence: 'DIRECT',
    client_ip: '192.168.1.15',
    client_port: 53100,
    server_ip: '10.0.0.25',
    server_port: 587,
    starttls_state: 'UPGRADED_TLS',
    capture_completeness: 100,
    packet_count: 34,
    byte_count: 12450,
    auth_observed: true,
    auth_plaintext: false,
    handshake: {
      handshake_id: 'hs-002',
      session_id: 'sess-002',
      version: 'TLS 1.3',
      cipher_suite: 'TLS_AES_256_GCM_SHA384',
      key_exchange: 'ECDHE',
      forward_secrecy: true,
      sni: 'mail.enterprise-relay.org',
      supported_groups: ['x25519', 'secp256r1'],
      session_resumption: true,
      handshake_sequence: ['ClientHello', 'ServerHello', 'ChangeCipherSpec', 'EncryptedExtensions', 'Finished'],
      alerts: [],
      duration_ms: 18.5,
      certificates: []
    }
  },
  {
    session_id: 'sess-003',
    capture_id: 'cap-demo-160',
    protocol: 'IMAP',
    protocol_confidence: 'DIRECT',
    client_ip: '192.168.1.50',
    client_port: 48920,
    server_ip: '10.0.0.25',
    server_port: 993,
    starttls_state: 'IMPLICIT_TLS',
    capture_completeness: 100,
    packet_count: 42,
    byte_count: 18320,
    auth_observed: true,
    auth_plaintext: false,
    handshake: {
      handshake_id: 'hs-003',
      session_id: 'sess-003',
      version: 'TLS 1.3',
      cipher_suite: 'TLS_AES_128_GCM_SHA256',
      key_exchange: 'ECDHE',
      forward_secrecy: true,
      sni: 'imap-secure.cluster.local',
      supported_groups: ['x25519'],
      session_resumption: false,
      handshake_sequence: ['ClientHello', 'ServerHello', 'EncryptedExtensions', 'Finished'],
      alerts: [],
      duration_ms: 22.1,
      certificates: []
    }
  },
  {
    session_id: 'sess-004',
    capture_id: 'cap-demo-160',
    protocol: 'IMAP',
    protocol_confidence: 'DIRECT',
    client_ip: '192.168.1.52',
    client_port: 49100,
    server_ip: '10.0.0.25',
    server_port: 143,
    starttls_state: 'UPGRADED_TLS',
    capture_completeness: 100,
    packet_count: 22,
    byte_count: 7600,
    auth_observed: true,
    auth_plaintext: false,
    handshake: {
      handshake_id: 'hs-004',
      session_id: 'sess-004',
      version: 'TLS 1.2',
      cipher_suite: 'TLS_RSA_WITH_3DES_EDE_CBC_SHA',
      key_exchange: 'RSA',
      forward_secrecy: false,
      sni: 'imap-secure.cluster.local',
      supported_groups: [],
      session_resumption: false,
      handshake_sequence: ['ClientHello', 'ServerHello', 'Certificate', 'ServerHelloDone'],
      alerts: [],
      duration_ms: 38.0,
      certificates: []
    }
  },
  {
    session_id: 'sess-007',
    capture_id: 'cap-demo-160',
    protocol: 'SMTP',
    protocol_confidence: 'DIRECT',
    client_ip: '192.168.1.99',
    client_port: 58210,
    server_ip: '10.0.0.25',
    server_port: 25,
    starttls_state: 'PLAINTEXT_FALLBACK',
    capture_completeness: 100,
    packet_count: 18,
    byte_count: 4200,
    auth_observed: true,
    auth_plaintext: true,
  },
  {
    session_id: 'sess-009',
    capture_id: 'cap-demo-160',
    protocol: 'POP3',
    protocol_confidence: 'DIRECT',
    client_ip: '192.168.1.104',
    client_port: 60120,
    server_ip: '10.0.0.25',
    server_port: 110,
    starttls_state: 'UPGRADED_TLS',
    capture_completeness: 100,
    packet_count: 25,
    byte_count: 9100,
    auth_observed: true,
    auth_plaintext: false,
    handshake: {
      handshake_id: 'hs-009',
      session_id: 'sess-009',
      version: 'TLS 1.2',
      cipher_suite: 'TLS_RSA_WITH_AES_128_CBC_SHA',
      key_exchange: 'RSA',
      forward_secrecy: false,
      sni: 'legacy-pop3.dept.local',
      supported_groups: [],
      session_resumption: false,
      handshake_sequence: ['ClientHello', 'ServerHello', 'Certificate'],
      alerts: [],
      duration_ms: 35.4,
      certificates: []
    }
  }
];
